print("Welcome to the tip calculator.")
total = input("What was the total bill? $")
tip = input("What percentage tip would you like to give? 10, 12, or 15? ")
people = input("How many people to split the bill? ")
summ = (((float(total) * (float(tip) / 100 ) + float(total) ) / float(people)))
print(f"Each person should pay: ${str(round(summ, 2))}")
